package io.github.asthenia0412.mocktpi.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class AdmissionDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public AdmissionDataExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUniversityIdIsNull() {
            addCriterion("university_id is null");
            return (Criteria) this;
        }

        public Criteria andUniversityIdIsNotNull() {
            addCriterion("university_id is not null");
            return (Criteria) this;
        }

        public Criteria andUniversityIdEqualTo(Long value) {
            addCriterion("university_id =", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdNotEqualTo(Long value) {
            addCriterion("university_id <>", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdGreaterThan(Long value) {
            addCriterion("university_id >", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("university_id >=", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdLessThan(Long value) {
            addCriterion("university_id <", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdLessThanOrEqualTo(Long value) {
            addCriterion("university_id <=", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdIn(List<Long> values) {
            addCriterion("university_id in", values, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdNotIn(List<Long> values) {
            addCriterion("university_id not in", values, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdBetween(Long value1, Long value2) {
            addCriterion("university_id between", value1, value2, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdNotBetween(Long value1, Long value2) {
            addCriterion("university_id not between", value1, value2, "universityId");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateIsNull() {
            addCriterion("admission_rate is null");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateIsNotNull() {
            addCriterion("admission_rate is not null");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateEqualTo(BigDecimal value) {
            addCriterion("admission_rate =", value, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateNotEqualTo(BigDecimal value) {
            addCriterion("admission_rate <>", value, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateGreaterThan(BigDecimal value) {
            addCriterion("admission_rate >", value, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("admission_rate >=", value, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateLessThan(BigDecimal value) {
            addCriterion("admission_rate <", value, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("admission_rate <=", value, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateIn(List<BigDecimal> values) {
            addCriterion("admission_rate in", values, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateNotIn(List<BigDecimal> values) {
            addCriterion("admission_rate not in", values, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("admission_rate between", value1, value2, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAdmissionRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("admission_rate not between", value1, value2, "admissionRate");
            return (Criteria) this;
        }

        public Criteria andAvgGpaIsNull() {
            addCriterion("avg_gpa is null");
            return (Criteria) this;
        }

        public Criteria andAvgGpaIsNotNull() {
            addCriterion("avg_gpa is not null");
            return (Criteria) this;
        }

        public Criteria andAvgGpaEqualTo(BigDecimal value) {
            addCriterion("avg_gpa =", value, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaNotEqualTo(BigDecimal value) {
            addCriterion("avg_gpa <>", value, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaGreaterThan(BigDecimal value) {
            addCriterion("avg_gpa >", value, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_gpa >=", value, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaLessThan(BigDecimal value) {
            addCriterion("avg_gpa <", value, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("avg_gpa <=", value, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaIn(List<BigDecimal> values) {
            addCriterion("avg_gpa in", values, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaNotIn(List<BigDecimal> values) {
            addCriterion("avg_gpa not in", values, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_gpa between", value1, value2, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andAvgGpaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("avg_gpa not between", value1, value2, "avgGpa");
            return (Criteria) this;
        }

        public Criteria andIntlRatioIsNull() {
            addCriterion("intl_ratio is null");
            return (Criteria) this;
        }

        public Criteria andIntlRatioIsNotNull() {
            addCriterion("intl_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andIntlRatioEqualTo(BigDecimal value) {
            addCriterion("intl_ratio =", value, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioNotEqualTo(BigDecimal value) {
            addCriterion("intl_ratio <>", value, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioGreaterThan(BigDecimal value) {
            addCriterion("intl_ratio >", value, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("intl_ratio >=", value, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioLessThan(BigDecimal value) {
            addCriterion("intl_ratio <", value, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("intl_ratio <=", value, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioIn(List<BigDecimal> values) {
            addCriterion("intl_ratio in", values, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioNotIn(List<BigDecimal> values) {
            addCriterion("intl_ratio not in", values, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("intl_ratio between", value1, value2, "intlRatio");
            return (Criteria) this;
        }

        public Criteria andIntlRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("intl_ratio not between", value1, value2, "intlRatio");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admission_data
     *
     * @mbg.generated do_not_delete_during_merge Sun Aug 17 16:28:15 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}