package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class AdmissionData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_data.admission_rate
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal admissionRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_data.avg_gpa
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal avgGpa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admission_data.intl_ratio
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal intlRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_data.id
     *
     * @return the value of admission_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_data.id
     *
     * @param id the value for admission_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_data.university_id
     *
     * @return the value of admission_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_data.university_id
     *
     * @param universityId the value for admission_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_data.admission_rate
     *
     * @return the value of admission_data.admission_rate
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getAdmissionRate() {
        return admissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_data.admission_rate
     *
     * @param admissionRate the value for admission_data.admission_rate
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setAdmissionRate(BigDecimal admissionRate) {
        this.admissionRate = admissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_data.avg_gpa
     *
     * @return the value of admission_data.avg_gpa
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getAvgGpa() {
        return avgGpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_data.avg_gpa
     *
     * @param avgGpa the value for admission_data.avg_gpa
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setAvgGpa(BigDecimal avgGpa) {
        this.avgGpa = avgGpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admission_data.intl_ratio
     *
     * @return the value of admission_data.intl_ratio
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getIntlRatio() {
        return intlRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admission_data.intl_ratio
     *
     * @param intlRatio the value for admission_data.intl_ratio
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setIntlRatio(BigDecimal intlRatio) {
        this.intlRatio = intlRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", admissionRate=").append(admissionRate);
        sb.append(", avgGpa=").append(avgGpa);
        sb.append(", intlRatio=").append(intlRatio);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}