package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   TPI录取信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table admission_data
 */
public class AdmissionData implements Serializable {
    private Long id;

    /**
     * 学校ID
     * 数据库字段: admission_data.university_id
     */
    private Long universityId;

    /**
     * 录取率
     * 数据库字段: admission_data.admission_rate
     */
    private BigDecimal admissionRate;

    /**
     * 平均GPA
     * 数据库字段: admission_data.avg_gpa
     */
    private BigDecimal avgGpa;

    /**
     * 国际学生比例
     * 数据库字段: admission_data.intl_ratio
     */
    private BigDecimal intlRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admission_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return id - 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取录取率
     * @return admission_rate - 录取率
     */
    public BigDecimal getAdmissionRate() {
        return admissionRate;
    }

    /**
     * 设置录取率
     * @param admissionRate 录取率
     */
    public void setAdmissionRate(BigDecimal admissionRate) {
        this.admissionRate = admissionRate;
    }

    /**
     * 获取平均GPA
     * @return avg_gpa - 平均GPA
     */
    public BigDecimal getAvgGpa() {
        return avgGpa;
    }

    /**
     * 设置平均GPA
     * @param avgGpa 平均GPA
     */
    public void setAvgGpa(BigDecimal avgGpa) {
        this.avgGpa = avgGpa;
    }

    /**
     * 获取国际学生比例
     * @return intl_ratio - 国际学生比例
     */
    public BigDecimal getIntlRatio() {
        return intlRatio;
    }

    /**
     * 设置国际学生比例
     * @param intlRatio 国际学生比例
     */
    public void setIntlRatio(BigDecimal intlRatio) {
        this.intlRatio = intlRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", admissionRate=").append(admissionRate);
        sb.append(", avgGpa=").append(avgGpa);
        sb.append(", intlRatio=").append(intlRatio);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}