package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   TPI校区信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table campus_data
 */
public class CampusData implements Serializable {
    private Long id;

    /**
     * 学校ID
     * 数据库字段: campus_data.university_id
     */
    private Long universityId;

    /**
     * 校区位置
     * 数据库字段: campus_data.location
     */
    private String location;

    /**
     * 纬度
     * 数据库字段: campus_data.latitude
     */
    private BigDecimal latitude;

    /**
     * 设施描述
     * 数据库字段: campus_data.facilities
     */
    private String facilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table campus_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return id - 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取校区位置
     * @return location - 校区位置
     */
    public String getLocation() {
        return location;
    }

    /**
     * 设置校区位置
     * @param location 校区位置
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * 获取纬度
     * @return latitude - 纬度
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * 设置纬度
     * @param latitude 纬度
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * 获取设施描述
     * @return facilities - 设施描述
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * 设置设施描述
     * @param facilities 设施描述
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", location=").append(location);
        sb.append(", latitude=").append(latitude);
        sb.append(", facilities=").append(facilities);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}