package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class CampusData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_data.location
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_data.latitude
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_data.facilities
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String facilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_data.id
     *
     * @return the value of campus_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_data.id
     *
     * @param id the value for campus_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_data.university_id
     *
     * @return the value of campus_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_data.university_id
     *
     * @param universityId the value for campus_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_data.location
     *
     * @return the value of campus_data.location
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_data.location
     *
     * @param location the value for campus_data.location
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_data.latitude
     *
     * @return the value of campus_data.latitude
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_data.latitude
     *
     * @param latitude the value for campus_data.latitude
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_data.facilities
     *
     * @return the value of campus_data.facilities
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getFacilities() {
        return facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_data.facilities
     *
     * @param facilities the value for campus_data.facilities
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setFacilities(String facilities) {
        this.facilities = facilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", location=").append(location);
        sb.append(", latitude=").append(latitude);
        sb.append(", facilities=").append(facilities);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}