package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.util.Date;

public class EventData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_data.event_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_data.event_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_data.start_time
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_data.event_id
     *
     * @return the value of event_data.event_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_data.event_id
     *
     * @param eventId the value for event_data.event_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_data.university_id
     *
     * @return the value of event_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_data.university_id
     *
     * @param universityId the value for event_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_data.event_type
     *
     * @return the value of event_data.event_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_data.event_type
     *
     * @param eventType the value for event_data.event_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_data.start_time
     *
     * @return the value of event_data.start_time
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_data.start_time
     *
     * @param startTime the value for event_data.start_time
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventId=").append(eventId);
        sb.append(", universityId=").append(universityId);
        sb.append(", eventType=").append(eventType);
        sb.append(", startTime=").append(startTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}