package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   TPI事件信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table event_data
 */
public class EventData implements Serializable {
    private Long eventId;

    /**
     * 学校ID
     * 数据库字段: event_data.university_id
     */
    private Long universityId;

    /**
     * 事件类型
     * 数据库字段: event_data.event_type
     */
    private String eventType;

    /**
     * 开始时间
     * 数据库字段: event_data.start_time
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table event_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return event_id - 
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * 设置
     * @param eventId 
     */
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取事件类型
     * @return event_type - 事件类型
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * 设置事件类型
     * @param eventType 事件类型
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * 获取开始时间
     * @return start_time - 开始时间
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * 设置开始时间
     * @param startTime 开始时间
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eventId=").append(eventId);
        sb.append(", universityId=").append(universityId);
        sb.append(", eventType=").append(eventType);
        sb.append(", startTime=").append(startTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}