package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   TPI院系信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table faculty_data
 */
public class FacultyData implements Serializable {
    private Long facultyId;

    /**
     * 学校ID
     * 数据库字段: faculty_data.university_id
     */
    private Long universityId;

    /**
     * 院系名称
     * 数据库字段: faculty_data.name
     */
    private String name;

    /**
     * 研究领域
     * 数据库字段: faculty_data.research_field
     */
    private String researchField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return faculty_id - 
     */
    public Long getFacultyId() {
        return facultyId;
    }

    /**
     * 设置
     * @param facultyId 
     */
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取院系名称
     * @return name - 院系名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置院系名称
     * @param name 院系名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取研究领域
     * @return research_field - 研究领域
     */
    public String getResearchField() {
        return researchField;
    }

    /**
     * 设置研究领域
     * @param researchField 研究领域
     */
    public void setResearchField(String researchField) {
        this.researchField = researchField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", facultyId=").append(facultyId);
        sb.append(", universityId=").append(universityId);
        sb.append(", name=").append(name);
        sb.append(", researchField=").append(researchField);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}