package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;

public class FacultyData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty_data.faculty_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long facultyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty_data.name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty_data.research_field
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String researchField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table faculty_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty_data.faculty_id
     *
     * @return the value of faculty_data.faculty_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getFacultyId() {
        return facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty_data.faculty_id
     *
     * @param facultyId the value for faculty_data.faculty_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty_data.university_id
     *
     * @return the value of faculty_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty_data.university_id
     *
     * @param universityId the value for faculty_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty_data.name
     *
     * @return the value of faculty_data.name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty_data.name
     *
     * @param name the value for faculty_data.name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty_data.research_field
     *
     * @return the value of faculty_data.research_field
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getResearchField() {
        return researchField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty_data.research_field
     *
     * @param researchField the value for faculty_data.research_field
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setResearchField(String researchField) {
        this.researchField = researchField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", facultyId=").append(facultyId);
        sb.append(", universityId=").append(universityId);
        sb.append(", name=").append(name);
        sb.append(", researchField=").append(researchField);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}