package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   TPI费用信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fee_data
 */
public class FeeData implements Serializable {
    private Long id;

    /**
     * 学校ID
     * 数据库字段: fee_data.university_id
     */
    private Long universityId;

    /**
     * 学费
     * 数据库字段: fee_data.tuition_fee
     */
    private BigDecimal tuitionFee;

    /**
     * 住宿费
     * 数据库字段: fee_data.accommodation_fee
     */
    private BigDecimal accommodationFee;

    /**
     * 年份
     * 数据库字段: fee_data.year
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fee_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return id - 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取学费
     * @return tuition_fee - 学费
     */
    public BigDecimal getTuitionFee() {
        return tuitionFee;
    }

    /**
     * 设置学费
     * @param tuitionFee 学费
     */
    public void setTuitionFee(BigDecimal tuitionFee) {
        this.tuitionFee = tuitionFee;
    }

    /**
     * 获取住宿费
     * @return accommodation_fee - 住宿费
     */
    public BigDecimal getAccommodationFee() {
        return accommodationFee;
    }

    /**
     * 设置住宿费
     * @param accommodationFee 住宿费
     */
    public void setAccommodationFee(BigDecimal accommodationFee) {
        this.accommodationFee = accommodationFee;
    }

    /**
     * 获取年份
     * @return year - 年份
     */
    public Integer getYear() {
        return year;
    }

    /**
     * 设置年份
     * @param year 年份
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", tuitionFee=").append(tuitionFee);
        sb.append(", accommodationFee=").append(accommodationFee);
        sb.append(", year=").append(year);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}