package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class FeeData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_data.tuition_fee
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal tuitionFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_data.accommodation_fee
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal accommodationFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fee_data.year
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_data.id
     *
     * @return the value of fee_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_data.id
     *
     * @param id the value for fee_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_data.university_id
     *
     * @return the value of fee_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_data.university_id
     *
     * @param universityId the value for fee_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_data.tuition_fee
     *
     * @return the value of fee_data.tuition_fee
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getTuitionFee() {
        return tuitionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_data.tuition_fee
     *
     * @param tuitionFee the value for fee_data.tuition_fee
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setTuitionFee(BigDecimal tuitionFee) {
        this.tuitionFee = tuitionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_data.accommodation_fee
     *
     * @return the value of fee_data.accommodation_fee
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getAccommodationFee() {
        return accommodationFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_data.accommodation_fee
     *
     * @param accommodationFee the value for fee_data.accommodation_fee
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setAccommodationFee(BigDecimal accommodationFee) {
        this.accommodationFee = accommodationFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fee_data.year
     *
     * @return the value of fee_data.year
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fee_data.year
     *
     * @param year the value for fee_data.year
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", tuitionFee=").append(tuitionFee);
        sb.append(", accommodationFee=").append(accommodationFee);
        sb.append(", year=").append(year);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}