package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   TPI合作关系表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table partner_data
 */
public class PartnerData implements Serializable {
    private Long id;

    /**
     * 学校ID
     * 数据库字段: partner_data.university_id
     */
    private Long universityId;

    /**
     * 合作机构名称
     * 数据库字段: partner_data.partner_name
     */
    private String partnerName;

    /**
     * 协议类型
     * 数据库字段: partner_data.agreement_type
     */
    private String agreementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return id - 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取合作机构名称
     * @return partner_name - 合作机构名称
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * 设置合作机构名称
     * @param partnerName 合作机构名称
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }

    /**
     * 获取协议类型
     * @return agreement_type - 协议类型
     */
    public String getAgreementType() {
        return agreementType;
    }

    /**
     * 设置协议类型
     * @param agreementType 协议类型
     */
    public void setAgreementType(String agreementType) {
        this.agreementType = agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", partnerName=").append(partnerName);
        sb.append(", agreementType=").append(agreementType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}