package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;

public class PartnerData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_data.partner_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String partnerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_data.agreement_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String agreementType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_data.id
     *
     * @return the value of partner_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_data.id
     *
     * @param id the value for partner_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_data.university_id
     *
     * @return the value of partner_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_data.university_id
     *
     * @param universityId the value for partner_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_data.partner_name
     *
     * @return the value of partner_data.partner_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_data.partner_name
     *
     * @param partnerName the value for partner_data.partner_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_data.agreement_type
     *
     * @return the value of partner_data.agreement_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getAgreementType() {
        return agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_data.agreement_type
     *
     * @param agreementType the value for partner_data.agreement_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setAgreementType(String agreementType) {
        this.agreementType = agreementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", partnerName=").append(partnerName);
        sb.append(", agreementType=").append(agreementType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}