package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   TPI项目信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table program_data
 */
public class ProgramData implements Serializable {
    private Long programId;

    /**
     * 学校ID
     * 数据库字段: program_data.university_id
     */
    private Long universityId;

    /**
     * 项目名称
     * 数据库字段: program_data.program_name
     */
    private String programName;

    /**
     * 学位类型
     * 数据库字段: program_data.degree_type
     */
    private String degreeType;

    /**
     * 学制（月）
     * 数据库字段: program_data.duration
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table program_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return program_id - 
     */
    public Long getProgramId() {
        return programId;
    }

    /**
     * 设置
     * @param programId 
     */
    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取项目名称
     * @return program_name - 项目名称
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * 设置项目名称
     * @param programName 项目名称
     */
    public void setProgramName(String programName) {
        this.programName = programName;
    }

    /**
     * 获取学位类型
     * @return degree_type - 学位类型
     */
    public String getDegreeType() {
        return degreeType;
    }

    /**
     * 设置学位类型
     * @param degreeType 学位类型
     */
    public void setDegreeType(String degreeType) {
        this.degreeType = degreeType;
    }

    /**
     * 获取学制（月）
     * @return duration - 学制（月）
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * 设置学制（月）
     * @param duration 学制（月）
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", programId=").append(programId);
        sb.append(", universityId=").append(universityId);
        sb.append(", programName=").append(programName);
        sb.append(", degreeType=").append(degreeType);
        sb.append(", duration=").append(duration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}