package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;

public class ProgramData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_data.program_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long programId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_data.program_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String programName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_data.degree_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String degreeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program_data.duration
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_data.program_id
     *
     * @return the value of program_data.program_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_data.program_id
     *
     * @param programId the value for program_data.program_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_data.university_id
     *
     * @return the value of program_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_data.university_id
     *
     * @param universityId the value for program_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_data.program_name
     *
     * @return the value of program_data.program_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_data.program_name
     *
     * @param programName the value for program_data.program_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setProgramName(String programName) {
        this.programName = programName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_data.degree_type
     *
     * @return the value of program_data.degree_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getDegreeType() {
        return degreeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_data.degree_type
     *
     * @param degreeType the value for program_data.degree_type
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setDegreeType(String degreeType) {
        this.degreeType = degreeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program_data.duration
     *
     * @return the value of program_data.duration
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program_data.duration
     *
     * @param duration the value for program_data.duration
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", programId=").append(programId);
        sb.append(", universityId=").append(universityId);
        sb.append(", programName=").append(programName);
        sb.append(", degreeType=").append(degreeType);
        sb.append(", duration=").append(duration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}