package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   TPI学校排名表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table qs_ranking_data
 */
public class QsRankingData implements Serializable {
    private Long id;

    /**
     * 学校名称
     * 数据库字段: qs_ranking_data.university_name
     */
    private String universityName;

    /**
     * QS排名
     * 数据库字段: qs_ranking_data.qs_rank
     */
    private Integer qsRank;

    /**
     * THE排名
     * 数据库字段: qs_ranking_data.the_rank
     */
    private Integer theRank;

    /**
     * 年份
     * 数据库字段: qs_ranking_data.year
     */
    private Integer year;

    /**
     * 创建时间
     * 数据库字段: qs_ranking_data.created_at
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qs_ranking_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return id - 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取学校名称
     * @return university_name - 学校名称
     */
    public String getUniversityName() {
        return universityName;
    }

    /**
     * 设置学校名称
     * @param universityName 学校名称
     */
    public void setUniversityName(String universityName) {
        this.universityName = universityName;
    }

    /**
     * 获取QS排名
     * @return qs_rank - QS排名
     */
    public Integer getQsRank() {
        return qsRank;
    }

    /**
     * 设置QS排名
     * @param qsRank QS排名
     */
    public void setQsRank(Integer qsRank) {
        this.qsRank = qsRank;
    }

    /**
     * 获取THE排名
     * @return the_rank - THE排名
     */
    public Integer getTheRank() {
        return theRank;
    }

    /**
     * 设置THE排名
     * @param theRank THE排名
     */
    public void setTheRank(Integer theRank) {
        this.theRank = theRank;
    }

    /**
     * 获取年份
     * @return year - 年份
     */
    public Integer getYear() {
        return year;
    }

    /**
     * 设置年份
     * @param year 年份
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * 获取创建时间
     * @return created_at - 创建时间
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * 设置创建时间
     * @param createdAt 创建时间
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityName=").append(universityName);
        sb.append(", qsRank=").append(qsRank);
        sb.append(", theRank=").append(theRank);
        sb.append(", year=").append(year);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}