package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.util.Date;

public class QsRankingData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qs_ranking_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qs_ranking_data.university_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String universityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qs_ranking_data.qs_rank
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Integer qsRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qs_ranking_data.the_rank
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Integer theRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qs_ranking_data.year
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qs_ranking_data.created_at
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qs_ranking_data.id
     *
     * @return the value of qs_ranking_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qs_ranking_data.id
     *
     * @param id the value for qs_ranking_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qs_ranking_data.university_name
     *
     * @return the value of qs_ranking_data.university_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getUniversityName() {
        return universityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qs_ranking_data.university_name
     *
     * @param universityName the value for qs_ranking_data.university_name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityName(String universityName) {
        this.universityName = universityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qs_ranking_data.qs_rank
     *
     * @return the value of qs_ranking_data.qs_rank
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Integer getQsRank() {
        return qsRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qs_ranking_data.qs_rank
     *
     * @param qsRank the value for qs_ranking_data.qs_rank
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setQsRank(Integer qsRank) {
        this.qsRank = qsRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qs_ranking_data.the_rank
     *
     * @return the value of qs_ranking_data.the_rank
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Integer getTheRank() {
        return theRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qs_ranking_data.the_rank
     *
     * @param theRank the value for qs_ranking_data.the_rank
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setTheRank(Integer theRank) {
        this.theRank = theRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qs_ranking_data.year
     *
     * @return the value of qs_ranking_data.year
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qs_ranking_data.year
     *
     * @param year the value for qs_ranking_data.year
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qs_ranking_data.created_at
     *
     * @return the value of qs_ranking_data.created_at
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qs_ranking_data.created_at
     *
     * @param createdAt the value for qs_ranking_data.created_at
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityName=").append(universityName);
        sb.append(", qsRank=").append(qsRank);
        sb.append(", theRank=").append(theRank);
        sb.append(", year=").append(year);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}