package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class RequirementData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement_data.ielts_min
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal ieltsMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement_data.toefl_min
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Integer toeflMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement_data.documents
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String documents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table requirement_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement_data.id
     *
     * @return the value of requirement_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement_data.id
     *
     * @param id the value for requirement_data.id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement_data.university_id
     *
     * @return the value of requirement_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement_data.university_id
     *
     * @param universityId the value for requirement_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement_data.ielts_min
     *
     * @return the value of requirement_data.ielts_min
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getIeltsMin() {
        return ieltsMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement_data.ielts_min
     *
     * @param ieltsMin the value for requirement_data.ielts_min
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setIeltsMin(BigDecimal ieltsMin) {
        this.ieltsMin = ieltsMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement_data.toefl_min
     *
     * @return the value of requirement_data.toefl_min
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Integer getToeflMin() {
        return toeflMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement_data.toefl_min
     *
     * @param toeflMin the value for requirement_data.toefl_min
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setToeflMin(Integer toeflMin) {
        this.toeflMin = toeflMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement_data.documents
     *
     * @return the value of requirement_data.documents
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getDocuments() {
        return documents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement_data.documents
     *
     * @param documents the value for requirement_data.documents
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setDocuments(String documents) {
        this.documents = documents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", ieltsMin=").append(ieltsMin);
        sb.append(", toeflMin=").append(toeflMin);
        sb.append(", documents=").append(documents);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}