package io.github.asthenia0412.mocktpi.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RequirementDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public RequirementDataExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * TPI入学要求表
     * 
     * @作者 Administrator
     * @日期 2025-08-17 16:54:10
     * @表名 requirement_data
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUniversityIdIsNull() {
            addCriterion("university_id is null");
            return (Criteria) this;
        }

        public Criteria andUniversityIdIsNotNull() {
            addCriterion("university_id is not null");
            return (Criteria) this;
        }

        public Criteria andUniversityIdEqualTo(Long value) {
            addCriterion("university_id =", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdNotEqualTo(Long value) {
            addCriterion("university_id <>", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdGreaterThan(Long value) {
            addCriterion("university_id >", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("university_id >=", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdLessThan(Long value) {
            addCriterion("university_id <", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdLessThanOrEqualTo(Long value) {
            addCriterion("university_id <=", value, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdIn(List<Long> values) {
            addCriterion("university_id in", values, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdNotIn(List<Long> values) {
            addCriterion("university_id not in", values, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdBetween(Long value1, Long value2) {
            addCriterion("university_id between", value1, value2, "universityId");
            return (Criteria) this;
        }

        public Criteria andUniversityIdNotBetween(Long value1, Long value2) {
            addCriterion("university_id not between", value1, value2, "universityId");
            return (Criteria) this;
        }

        public Criteria andIeltsMinIsNull() {
            addCriterion("ielts_min is null");
            return (Criteria) this;
        }

        public Criteria andIeltsMinIsNotNull() {
            addCriterion("ielts_min is not null");
            return (Criteria) this;
        }

        public Criteria andIeltsMinEqualTo(BigDecimal value) {
            addCriterion("ielts_min =", value, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinNotEqualTo(BigDecimal value) {
            addCriterion("ielts_min <>", value, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinGreaterThan(BigDecimal value) {
            addCriterion("ielts_min >", value, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ielts_min >=", value, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinLessThan(BigDecimal value) {
            addCriterion("ielts_min <", value, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ielts_min <=", value, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinIn(List<BigDecimal> values) {
            addCriterion("ielts_min in", values, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinNotIn(List<BigDecimal> values) {
            addCriterion("ielts_min not in", values, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ielts_min between", value1, value2, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andIeltsMinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ielts_min not between", value1, value2, "ieltsMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinIsNull() {
            addCriterion("toefl_min is null");
            return (Criteria) this;
        }

        public Criteria andToeflMinIsNotNull() {
            addCriterion("toefl_min is not null");
            return (Criteria) this;
        }

        public Criteria andToeflMinEqualTo(Integer value) {
            addCriterion("toefl_min =", value, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinNotEqualTo(Integer value) {
            addCriterion("toefl_min <>", value, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinGreaterThan(Integer value) {
            addCriterion("toefl_min >", value, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("toefl_min >=", value, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinLessThan(Integer value) {
            addCriterion("toefl_min <", value, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinLessThanOrEqualTo(Integer value) {
            addCriterion("toefl_min <=", value, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinIn(List<Integer> values) {
            addCriterion("toefl_min in", values, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinNotIn(List<Integer> values) {
            addCriterion("toefl_min not in", values, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinBetween(Integer value1, Integer value2) {
            addCriterion("toefl_min between", value1, value2, "toeflMin");
            return (Criteria) this;
        }

        public Criteria andToeflMinNotBetween(Integer value1, Integer value2) {
            addCriterion("toefl_min not between", value1, value2, "toeflMin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table requirement_data
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * TPI入学要求表
     * 
     * @作者 Administrator
     * @日期 2025-08-17 16:54:10
     * @表名 requirement_data
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}