package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   TPI入学要求表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table requirement_data
 */
public class RequirementData implements Serializable {
    private Long id;

    /**
     * 学校ID
     * 数据库字段: requirement_data.university_id
     */
    private Long universityId;

    /**
     * 雅思最低分
     * 数据库字段: requirement_data.ielts_min
     */
    private BigDecimal ieltsMin;

    /**
     * 托福最低分
     * 数据库字段: requirement_data.toefl_min
     */
    private Integer toeflMin;

    /**
     * 所需材料
     * 数据库字段: requirement_data.documents
     */
    private String documents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return id - 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置
     * @param id 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取雅思最低分
     * @return ielts_min - 雅思最低分
     */
    public BigDecimal getIeltsMin() {
        return ieltsMin;
    }

    /**
     * 设置雅思最低分
     * @param ieltsMin 雅思最低分
     */
    public void setIeltsMin(BigDecimal ieltsMin) {
        this.ieltsMin = ieltsMin;
    }

    /**
     * 获取托福最低分
     * @return toefl_min - 托福最低分
     */
    public Integer getToeflMin() {
        return toeflMin;
    }

    /**
     * 设置托福最低分
     * @param toeflMin 托福最低分
     */
    public void setToeflMin(Integer toeflMin) {
        this.toeflMin = toeflMin;
    }

    /**
     * 获取所需材料
     * @return documents - 所需材料
     */
    public String getDocuments() {
        return documents;
    }

    /**
     * 设置所需材料
     * @param documents 所需材料
     */
    public void setDocuments(String documents) {
        this.documents = documents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", universityId=").append(universityId);
        sb.append(", ieltsMin=").append(ieltsMin);
        sb.append(", toeflMin=").append(toeflMin);
        sb.append(", documents=").append(documents);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}