package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ScholarshipData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship_data.scholarship_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long scholarshipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship_data.name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship_data.amount
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scholarship_data.deadline
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship_data.scholarship_id
     *
     * @return the value of scholarship_data.scholarship_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getScholarshipId() {
        return scholarshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship_data.scholarship_id
     *
     * @param scholarshipId the value for scholarship_data.scholarship_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setScholarshipId(Long scholarshipId) {
        this.scholarshipId = scholarshipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship_data.university_id
     *
     * @return the value of scholarship_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship_data.university_id
     *
     * @param universityId the value for scholarship_data.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship_data.name
     *
     * @return the value of scholarship_data.name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship_data.name
     *
     * @param name the value for scholarship_data.name
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship_data.amount
     *
     * @return the value of scholarship_data.amount
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship_data.amount
     *
     * @param amount the value for scholarship_data.amount
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scholarship_data.deadline
     *
     * @return the value of scholarship_data.deadline
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scholarship_data.deadline
     *
     * @param deadline the value for scholarship_data.deadline
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scholarshipId=").append(scholarshipId);
        sb.append(", universityId=").append(universityId);
        sb.append(", name=").append(name);
        sb.append(", amount=").append(amount);
        sb.append(", deadline=").append(deadline);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}