package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   TPI奖学金信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table scholarship_data
 */
public class ScholarshipData implements Serializable {
    private Long scholarshipId;

    /**
     * 学校ID
     * 数据库字段: scholarship_data.university_id
     */
    private Long universityId;

    /**
     * 奖学金名称
     * 数据库字段: scholarship_data.name
     */
    private String name;

    /**
     * 奖学金金额
     * 数据库字段: scholarship_data.amount
     */
    private BigDecimal amount;

    /**
     * 申请截止日期
     * 数据库字段: scholarship_data.deadline
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scholarship_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return scholarship_id - 
     */
    public Long getScholarshipId() {
        return scholarshipId;
    }

    /**
     * 设置
     * @param scholarshipId 
     */
    public void setScholarshipId(Long scholarshipId) {
        this.scholarshipId = scholarshipId;
    }

    /**
     * 获取学校ID
     * @return university_id - 学校ID
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置学校ID
     * @param universityId 学校ID
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取奖学金名称
     * @return name - 奖学金名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置奖学金名称
     * @param name 奖学金名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取奖学金金额
     * @return amount - 奖学金金额
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * 设置奖学金金额
     * @param amount 奖学金金额
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * 获取申请截止日期
     * @return deadline - 申请截止日期
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * 设置申请截止日期
     * @param deadline 申请截止日期
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scholarshipId=").append(scholarshipId);
        sb.append(", universityId=").append(universityId);
        sb.append(", name=").append(name);
        sb.append(", amount=").append(amount);
        sb.append(", deadline=").append(deadline);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}