package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   学校核心信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table university_core
 */
public class UniversityCore implements Serializable {
    private Long universityId;

    /**
     * 标准化学校名称
     * 数据库字段: university_core.name_std
     */
    private String nameStd;

    /**
     * 国家代码
     * 数据库字段: university_core.country_code
     */
    private String countryCode;

    /**
     * 数据来源
     * 数据库字段: university_core.data_source
     */
    private String dataSource;

    /**
     * 原始ID
     * 数据库字段: university_core.original_id
     */
    private String originalId;

    /**
     * 状态
     * 数据库字段: university_core.status
     */
    private String status;

    /**
     * 最后合并时间
     * 数据库字段: university_core.last_merge_time
     */
    private Date lastMergeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table university_core
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取
     * @return university_id - 
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * 设置
     * @param universityId 
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * 获取标准化学校名称
     * @return name_std - 标准化学校名称
     */
    public String getNameStd() {
        return nameStd;
    }

    /**
     * 设置标准化学校名称
     * @param nameStd 标准化学校名称
     */
    public void setNameStd(String nameStd) {
        this.nameStd = nameStd;
    }

    /**
     * 获取国家代码
     * @return country_code - 国家代码
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * 设置国家代码
     * @param countryCode 国家代码
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * 获取数据来源
     * @return data_source - 数据来源
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * 设置数据来源
     * @param dataSource 数据来源
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * 获取原始ID
     * @return original_id - 原始ID
     */
    public String getOriginalId() {
        return originalId;
    }

    /**
     * 设置原始ID
     * @param originalId 原始ID
     */
    public void setOriginalId(String originalId) {
        this.originalId = originalId;
    }

    /**
     * 获取状态
     * @return status - 状态
     */
    public String getStatus() {
        return status;
    }

    /**
     * 设置状态
     * @param status 状态
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取最后合并时间
     * @return last_merge_time - 最后合并时间
     */
    public Date getLastMergeTime() {
        return lastMergeTime;
    }

    /**
     * 设置最后合并时间
     * @param lastMergeTime 最后合并时间
     */
    public void setLastMergeTime(Date lastMergeTime) {
        this.lastMergeTime = lastMergeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", universityId=").append(universityId);
        sb.append(", nameStd=").append(nameStd);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", dataSource=").append(dataSource);
        sb.append(", originalId=").append(originalId);
        sb.append(", status=").append(status);
        sb.append(", lastMergeTime=").append(lastMergeTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}