package io.github.asthenia0412.mocktpi.model;

import java.io.Serializable;
import java.util.Date;

public class UniversityCore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Long universityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.name_std
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String nameStd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.country_code
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.data_source
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String dataSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.original_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.status
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column university_core.last_merge_time
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private Date lastMergeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table university_core
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.university_id
     *
     * @return the value of university_core.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.university_id
     *
     * @param universityId the value for university_core.university_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.name_std
     *
     * @return the value of university_core.name_std
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getNameStd() {
        return nameStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.name_std
     *
     * @param nameStd the value for university_core.name_std
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setNameStd(String nameStd) {
        this.nameStd = nameStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.country_code
     *
     * @return the value of university_core.country_code
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.country_code
     *
     * @param countryCode the value for university_core.country_code
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.data_source
     *
     * @return the value of university_core.data_source
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.data_source
     *
     * @param dataSource the value for university_core.data_source
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.original_id
     *
     * @return the value of university_core.original_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.original_id
     *
     * @param originalId the value for university_core.original_id
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setOriginalId(String originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.status
     *
     * @return the value of university_core.status
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.status
     *
     * @param status the value for university_core.status
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column university_core.last_merge_time
     *
     * @return the value of university_core.last_merge_time
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public Date getLastMergeTime() {
        return lastMergeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column university_core.last_merge_time
     *
     * @param lastMergeTime the value for university_core.last_merge_time
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    public void setLastMergeTime(Date lastMergeTime) {
        this.lastMergeTime = lastMergeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", universityId=").append(universityId);
        sb.append(", nameStd=").append(nameStd);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", dataSource=").append(dataSource);
        sb.append(", originalId=").append(originalId);
        sb.append(", status=").append(status);
        sb.append(", lastMergeTime=").append(lastMergeTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}