package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.AdmissionData;
import io.github.asthenia0412.mocktpi.model.AdmissionDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdmissionDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(AdmissionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(AdmissionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(AdmissionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(AdmissionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<AdmissionData> selectByExample(AdmissionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    AdmissionData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") AdmissionData record, @Param("example") AdmissionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") AdmissionData record, @Param("example") AdmissionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(AdmissionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admission_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(AdmissionData record);
}