package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.CampusData;
import io.github.asthenia0412.mocktpi.model.CampusDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampusDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(CampusData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(CampusData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<CampusData> selectByExampleWithBLOBs(CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<CampusData> selectByExample(CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    CampusData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") CampusData record, @Param("example") CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("record") CampusData record, @Param("example") CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") CampusData record, @Param("example") CampusDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(CampusData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(CampusData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(CampusData record);
}