package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.EventData;
import io.github.asthenia0412.mocktpi.model.EventDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    long countByExample(EventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int deleteByExample(EventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int insert(EventData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int insertSelective(EventData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    List<EventData> selectByExample(EventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    EventData selectByPrimaryKey(Long eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EventData record, @Param("example") EventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EventData record, @Param("example") EventDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EventData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventData record);
}