package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.FacultyData;
import io.github.asthenia0412.mocktpi.model.FacultyDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FacultyDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    long countByExample(FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int deleteByExample(FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long facultyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int insert(FacultyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int insertSelective(FacultyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    List<FacultyData> selectByExampleWithBLOBs(FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    List<FacultyData> selectByExample(FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    FacultyData selectByPrimaryKey(Long facultyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FacultyData record, @Param("example") FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FacultyData record, @Param("example") FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FacultyData record, @Param("example") FacultyDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FacultyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FacultyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table faculty_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FacultyData record);
}