package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.FeeData;
import io.github.asthenia0412.mocktpi.model.FeeDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(FeeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(FeeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(FeeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(FeeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<FeeData> selectByExample(FeeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    FeeData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") FeeData record, @Param("example") FeeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") FeeData record, @Param("example") FeeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(FeeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fee_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(FeeData record);
}