package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.PartnerData;
import io.github.asthenia0412.mocktpi.model.PartnerDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(PartnerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(PartnerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(PartnerData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(PartnerData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<PartnerData> selectByExample(PartnerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    PartnerData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") PartnerData record, @Param("example") PartnerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") PartnerData record, @Param("example") PartnerDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(PartnerData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(PartnerData record);
}