package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.ProgramData;
import io.github.asthenia0412.mocktpi.model.ProgramDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgramDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(ProgramDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(ProgramDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long programId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(ProgramData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(ProgramData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<ProgramData> selectByExample(ProgramDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    ProgramData selectByPrimaryKey(Long programId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") ProgramData record, @Param("example") ProgramDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") ProgramData record, @Param("example") ProgramDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(ProgramData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(ProgramData record);
}