package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.QsRankingData;
import io.github.asthenia0412.mocktpi.model.QsRankingDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QsRankingDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(QsRankingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(QsRankingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(QsRankingData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(QsRankingData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<QsRankingData> selectByExample(QsRankingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    QsRankingData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") QsRankingData record, @Param("example") QsRankingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") QsRankingData record, @Param("example") QsRankingDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(QsRankingData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qs_ranking_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(QsRankingData record);
}