package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.RequirementData;
import io.github.asthenia0412.mocktpi.model.RequirementDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequirementDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    long countByExample(RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int deleteByExample(RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int insert(RequirementData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int insertSelective(RequirementData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    List<RequirementData> selectByExampleWithBLOBs(RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    List<RequirementData> selectByExample(RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    RequirementData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RequirementData record, @Param("example") RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") RequirementData record, @Param("example") RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RequirementData record, @Param("example") RequirementDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequirementData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(RequirementData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table requirement_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequirementData record);
}