package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.ScholarshipData;
import io.github.asthenia0412.mocktpi.model.ScholarshipDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScholarshipDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    long countByExample(ScholarshipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByExample(ScholarshipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int deleteByPrimaryKey(Long scholarshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insert(ScholarshipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int insertSelective(ScholarshipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    List<ScholarshipData> selectByExample(ScholarshipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    ScholarshipData selectByPrimaryKey(Long scholarshipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExampleSelective(@Param("record") ScholarshipData record, @Param("example") ScholarshipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByExample(@Param("record") ScholarshipData record, @Param("example") ScholarshipDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKeySelective(ScholarshipData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scholarship_data
     *
     * @mbg.generated Sun Aug 17 16:28:15 CST 2025
     */
    int updateByPrimaryKey(ScholarshipData record);
}