package io.github.asthenia0412.mocktpi.mapper;

import io.github.asthenia0412.mocktpi.model.UniversityCore;
import io.github.asthenia0412.mocktpi.model.UniversityCoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UniversityCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    long countByExample(UniversityCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int deleteByExample(UniversityCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long universityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int insert(UniversityCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int insertSelective(UniversityCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    List<UniversityCore> selectByExample(UniversityCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    UniversityCore selectByPrimaryKey(Long universityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UniversityCore record, @Param("example") UniversityCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UniversityCore record, @Param("example") UniversityCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UniversityCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table university_core
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UniversityCore record);
}